### ISSUE TITLE
在执行react-native run-android的时候出现Could not run adb reverse的错误，环境变量是配置好了的

### ISSUE THREAD

**Issue by yvonnegithub** [ZevenFang/react-native-redux-zhihudaily#3]
<img width="933" alt="adberror" src="https://cloud.githubusercontent.com/assets/21054948/25847935/c46ca03a-34ea-11e7-8dd7-0f792420c323.png">

**Comment by ZevenFang** [comment]
你试一下重启adb
adb kill-server
adb start-server
