### ISSUE TITLE
启动ios仍然报错，reloadjs也不起作用，代码已经更新

### ISSUE THREAD

**Issue by yvonnegithub** [ZevenFang/react-native-redux-zhihudaily#5]
<img width="376" alt="newbug" src="https://cloud.githubusercontent.com/assets/21054948/26236594/ba785716-3ca3-11e7-8a27-5eea0dbf6570.png">

**Comment by ZevenFang** [comment]
报错原因应该是[这段代码](https://github.com/ZevenFang/react-native-redux-zhihudaily/blob/master/src/containers/App.js#L17-L29)造成的，从 [AsyncStorage](http://reactnative.cn/docs/0.44/asyncstorage.html#content) 异步获取不到保存的主题，进入主页面导致报错，已经在 store 中设置了默认值。

**Comment by ZevenFang** [comment]
现在这个版本在iOS上显示效果不佳，后面本项目将会用我最近写的 [脚手架](https://github.com/ZevenFang/react-native-starterkit) 重构，脚手架使用 [dva](https://github.com/dvajs/dva) + [nativebase](https://github.com/GeekyAnts/NativeBase) + [create-react-native-app](https://github.com/react-community/create-react-native-app) 等框架，相信在界面和稳定性方面会更加优秀。
