### ISSUE TITLE
请问代码里请求的api是真实知乎日报的api吗？怎么获取的？

### ISSUE THREAD

**Issue by yvonnegithub** [ZevenFang/react-native-redux-zhihudaily#6]

**Comment by ZevenFang** [comment]
[知乎日报 API 分析](https://github.com/izzyleung/ZhihuDailyPurify/wiki/%E7%9F%A5%E4%B9%8E%E6%97%A5%E6%8A%A5-API-%E5%88%86%E6%9E%90)
